# Generated by Django 6.0.2 on 2026-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Numéro Mobile Money"
            ),
        ),
    ]
