# Generated by Django 6.0.2 on 2026-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="moneroo_checkout_url",
            field=models.URLField(blank=True, verbose_name="URL de paiement Moneroo"),
        ),
        migrations.AddField(
            model_name="order",
            name="moneroo_payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID Moneroo"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("awaiting_payment", "En attente de paiement"),
                    ("confirmed", "Confirmée"),
                    ("processing", "En préparation"),
                    ("shipped", "Expédiée"),
                    ("delivered", "Livrée"),
                    ("cancelled", "Annulée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
