# Generated by Django 6.0.2 on 2026-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL de l'image (internet)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Prix (FC)"
            ),
        ),
    ]
